### PR TITLE
chore: update actions for trusted pub & 3.12

### PR DESCRIPTION
**Pull request by henryiii**
Adding 3.12 & trusted pub.

### CODE REVIEW

**Comment by henryiii** [comment]
@jcfr Same thing here, could you add trusted pub to PyPI?

**Comment by jcfr** [comment]
> Same thing here, could you add trusted pub to PyPI?

It looks I may have omitted to accept the invite, that said I just asked our sysadmin (aka @kwrobot) to add me as a owner,

Once this is done I will also add you as a owner of the project.

**Comment by jcfr** [comment]
All set. Publisher has been added.

**Comment by jcfr** [comment]
> Once this is done I will also add you as a owner of the project

You should have received an invite as well.

**Pull request merged**
