### PR TITLE
:bookmark: 3.17

### PR DESCRIPTION
**Pull request by jtxa**
There was an update in 3.17, in 3.18 it's still the same

### CODE REVIEW

**Comment by bruxisma** [comment]
Thanks for this! I'll still need to push an update to PyPI in a bit. If you don't see it by the end of the weekend, please ping me. Life has gotten *very* busy for me 😅

**Comment by jtxa** [comment]
No problem. CMake updated to Sphinx 2.4 so I thought there might be some changes. But these were unrelated.

**Comment by henryiii** [comment]
@slurps-mad-rips Ping! Any chance the PyPI package could get pushed? :)

**Comment by bruxisma** [comment]
ack! i totally missed this in my mentions. I'll try to get this released. ASAP. Sorry! :(

**Comment by bruxisma** [comment]
Release is up. Sorry about the long delay @henryiii and @jtxa 😓

**Pull request merged**
