### PR TITLE
Replace deprecated sphinx.testing.path with pathlib.Path

### PR DESCRIPTION
**Pull request by roehling**
This PR gets rid of a deprecation warning with Sphinx 7

### CODE REVIEW

**Comment by kloczek** [comment]
Just tested this PR and looks like it fixes test suite issue.
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-sphinxcontrib-moderncmakedomain-3.27.0-2.fc36.x86_64/usr/lib64/python3.9/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-sphinxcontrib-moderncmakedomain-3.27.0-2.fc36.x86_64/usr/lib/python3.9/site-packages
+ /usr/bin/pytest -ra -m 'not network'
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.9.18, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/tkloczko/rpmbuild/BUILD/moderncmakedomain-3.27.0
configfile: pyproject.toml
testpaths: tests
collected 4 items

tests/test_basic.py ...                                                                                                                                                               [ 75%]
tests/test_version.py .                                                                                                                                                               [100%]

===================================================================================== 4 passed in 1.01s =====================================================================================
```
It would be good to merge this PR.

**Comment by henryiii** [comment]
Thanks!

**Comment by henryiii** [comment]
This broke the tests. .copytree is not part of pathlib.

**Comment by henryiii** [comment]
7.3 (Python 3.9+) supports Path.

**Pull request merged**
